### ISSUE TITLE
User uniqueness test missing

### ISSUE THREAD

**Issue by Boerrild** [AxonFramework/Axon-trader#19]
In the architecture wiki document you state that:

> One important part for the users of the system is that the username's must be unique. When receiving a command to create a new user, we first check against a special collection to see if the username is still available. After validation we actually create the user.

However, I cannot find that check in the code, and I can easily create a test that attempt to create two users with the same username.

``` java
    @Test
    public void testHandleCreateUserTwice() throws Exception {
        UserId aggregateIdentifier = new UserId();

        UserEntry userEntry = new UserEntry();
        userEntry.setUsername("buyer1");
        userEntry.setIdentifier(aggregateIdentifier.toString());
        userEntry.setName("Buyer One");
        Mockito.when(userQueryRepository.findByUsername("buyer1")).thenReturn(userEntry);

        fixture.given(new UserCreatedEvent(aggregateIdentifier, "Buyer 1", "buyer1", DigestUtils.sha1("buyer1")))
                .when(new CreateUserCommand(aggregateIdentifier, "Buyer 1", "buyer1", "buyer1"))
                .expectEvents();
    }
```

The test gives:

```
-------------------------------------------------------------------------------
Test set: org.axonframework.samples.trader.app.command.user.UserCommandHandlerTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.355 sec <<< FAILURE!
testHandleCreateUserTwice(org.axonframework.samples.trader.app.command.user.UserCommandHandlerTest)  Time elapsed: 0.298 sec  <<< FAILURE!
org.axonframework.test.AxonAssertionError: The published events do not match the expected events

Expected  |  Actual
----------|----------
         <|> org.axonframework.samples.trader.api.users.UserCreatedEvent
```

**Comment by redhead** [comment]
What exactly should we query against? Shouldn't the check be in the domain instead of the query model?

**Comment by abuijze** [comment]
The check itself can be in the domain model, but the query model could
provide the data necessary. In the case of unique users, you'd simply query
for users with the ID of the user being created. If anything pops up, you
reject the command.

**Comment by redhead** [comment]
Ok. I am asking specifically about "purity" side of CQRS. So it is ok to check constraints using query model build by the events and not using aggregates. (Using aggregates seems like hell though - e.g. find a user aggregate that already has the same e-mail assigned)

**Comment by abuijze** [comment]
The aggregates are meant for handling commands. The essence of CQRS is that
you have a specific model for queries. Finding out if a user already exists
is a query, and thus uses a query model optimized to answer that question.

**Comment by eliezerb2** [comment]
Hi,
Any new information regarding this question?
Thanks

**Comment by smcvb** [comment]
Thanks for showing interest @eliezerb2, but no there are no new developments happening on user uniqueness for this sample, or any adjustments on this sample to begin with. We have actually been working on a more fleshed out example of almost _anything_ Axon, which you can find [here](https://github.com/AxonIQ/hotel-demo). So if you are looking for a sample application, I would refer you to that one as it does entail active development right now.

When it comes to this exact issue, this is nothing more than set based validation in a CQRS system. As the Aggregate does not entail sets (virtually ever), you wouldn't use the Aggregate directly for the validation. Instead, you would add another model to the overall Command Model which knows about the set of users to perform this set validation with. Importantly here is that this model is updated in the same transaction as which updates your Aggregates, to ensure consistency. As it stands we are actually working on a blog about Set Based Validation, so I would stay tuned towards that if you are interested in more.

Hoping that clarifies things for your @eliezerb2. Any how, this issue will remain closed as we are not aiming to provide any new features to this sample.

**Comment by eliezerb2** [comment]
How do update this model in the same transaction with the Aggregate? Is there any Axon capability I can use for doing that?
Thanks

**Comment by smcvb** [comment]
You can use Axon components to get this going, yes. As stated we are working on a blog about it, hence specifying it's not a simple answer I can drop right here which will give you a fool proof solution. 

I'd like you to tune in for this blog once we publish it (assuming this year).
Or if you don't have the time to wait, drop a question on our [forum](https://discuss.axoniq.io/) for that matter, so that the entire community can chip in. We aim to keep GitHub clear of usage questions (like this), hence the suggestion.

**Comment by eliezerb2** [comment]
Thanks
