### ISSUE TITLE
some question with axon

### ISSUE THREAD

**Issue by weechang** [AxonFramework/Axon-trader#25]
hi.I am very interested in axon.But I have some questions. i hope u can help me
1. when i want create a new user, but, user name is unique . in the create command, should  i to  do something? what should i do?

**Comment by abuijze** [comment]
You'd probably want to check out Greg Young's blog for this: http://codebetter.com/gregyoung/2010/08/12/eventual-consistency-and-set-validation/

For Axon related questions, please refer to www.axonframework.org/group or axonframework@googlegroups.com

Thanks.
