### ISSUE TITLE
Update Application to Axon Framework best practices

### ISSUE THREAD

**Issue by smcvb** [AxonFramework/Axon-trader#28]
For Axon Framework users it's beneficial to see an Axon Framework application which follows (what we regard) the best practices of such an application.
This work will thus entail stuff like:

- Updating most/all versions to the latest, especially the framework version.
- Incorporate Kotlin for the `core-api` module, as this provides a more concise solution for immutable objects.
- Introduce `@QueryHandler` annotated functions to Query Handling Components.
- Move the `@CommandHandler` annotations to the Aggregates i.o. a separate Command Handling Component.
- Use the `@EventSourcingHandler` annotation in Aggregates i.o. the `@EventHandler` annotation.
- Steam line configuration classes by using several of the automatically created beans through a Spring Boot Axon application.
- An overall style code update of all the classes.
- And very likely, a whole bunch of other adjustments as well.

**Comment by jorgheymans** [comment]
good to see acknowledgment that this example app is not really a showcase on how to use Axon best-practice :)

**Comment by xiangminghu** [comment]
@smcvb Steven, I couldn't find examples for @QueryHandler.  Has it be added?

**Comment by smcvb** [comment]
@xiangminghu this has not been added yet, but likely will be somewhere in the near future.
Your best bet to get going with the `@QueryHandler` annotation would be to have a look at the [Query Handling section](https://docs.axonframework.org/part-ii-domain-logic/query-handling) in the Ref. Guide for now.
